export const siteConfig = {
  name: "Guillaume Gabriel | Developer Portfolio",
  authorName: "Guillaume Gabriel",
  username: "guillaumeGabriel",
  description:
    "Guillaume Gabriel's portfolio - A modern, responsive Next.js portfolio for developers. This open-source template can be customized to showcase your own skills, projects, and professional experience.",
//  jobTitle: "Full Stack Developer",
//  jobDescription: "Développeur Fullstack passioné par le développement Web et le DevOps. Fort de mon expérience en entreprise je vous accompagne dans vos projets en France ou à l'international en React/NextJS ",
  url: "https://ggabriel-portfolio-nextjs.vercel.app",
  ogImage: "https://ggabriel-portfolio-nextjs.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fprofile-img.9d003a0a.jpg&w=828&q=75",
  iconIco: "/favicon.ico",
  logoIcon: "/favicon.ico",
  keywords: [
    "Guillaume Gabriel",
    "Full Stack Developer",
    "Web Developer Portfolio",
    "Next.js portfolio template",
    "React portfolio template",
    "Developer portfolio template",
    "Portfolio website template",
    "Next.js template",
    "Modern portfolio website",
    "Frontend developer portfolio",
    "Full stack developer portfolio",
    "Open source portfolio template",
    "Web developer portfolio template",
    "Responsive portfolio template",
    "React.js portfolio",
    "Tailwind CSS portfolio",
    "Developer showcase template",
    "Free portfolio template",
    "Next.js 13 template",
    "Shadcn UI template",
    "Career timeline template",
    "Portfolio with dark mode",
    "GitHub portfolio template",
  ],
};
